lib/smart_app_launch/ehr_launch_group.rb
lib/smart_app_launch/openid_fhir_user_claim_test.rb
lib/smart_app_launch/standalone_launch_group.rb
lib/smart_app_launch/token_exchange_test.rb
lib/smart_app_launch/token_refresh_test.rb
lib/smart_app_launch_test_kit.rb
spec/smart_app_launch/openid_connect_group_spec.rb
spec/smart_app_launch/openid_fhir_user_claim_test_spec.rb
spec/smart_app_launch/token_exchange_test_spec.rb

Update test kit to output `oauth_credentials` so fhir client tokens can automatically refresh.

FI-1407: Use oauth_credentials

---

lib/smart_app_launch/token_payload_validation.rb
lib/smart_app_launch/token_refresh_body_test.rb
lib/smart_app_launch/token_refresh_group.rb
spec/smart_app_launch/token_refresh_body_test_spec.rb

The current refresh token body test checks that granted refresh token scopes are _fully equivalent_ to the originally granted scopes. This PR relaxes that check to ensure that granted refresh tokens are a _strict subset_ of the originally granted scopes.
Note: We'll need to update the `.gempspec` in the g10 to use this once we have this approved and a new version published.
References:
https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/39
https://github.com/onc-healthit/inferno/issues/464
https://jira.hl7.org/browse/FHIR-36272
https://chat.fhir.org/#narrow/stream/179170-smart/topic/Expected.20scopes.20on.20a.20.22refreshed.22.20access.20token

FI-1490: Validate Granted Refresh Scopes are Subset of Originally Granted Scopes

---

.github/workflows/ruby.yml

While opening another PR I realized we don't have GitHub Actions running on this repo. Rubocop isn't set up on this testkit (should it be?), but we can at least run the tests.
I largely copied the workflow configuration from inferno-core.

Enable GitHub Actions

---

lib/smart_app_launch/app_redirect_test.rb
spec/smart_app_launch/app_redirect_test_spec.rb

* original bug seen from production logs
* using URI stdlib over string manipulation
* added tests

Fix authorization url building where a URL parameter could be a nil value

---

lib/smart_app_launch/discovery_group.rb
spec/smart_app_launch/discovery_group_spec.rb

Adds an `Accept: application/json` header to the `FHIR server makes SMART configuration available from well-known endpoint` test.

FI-1563 `.well-known/smart-configuration` Request Accept Header

---

config/presets/inferno_reference_server_stu2_preset.json
lib/smart_app_launch/app_redirect_test_stu2.rb
lib/smart_app_launch/ehr_launch_group_stu2.rb
lib/smart_app_launch/post_auth.html
lib/smart_app_launch/smart_stu2_suite.rb
lib/smart_app_launch/standalone_launch_group_stu2.rb
smart_app_launch_test_kit.gemspec

This branch adds support for using POST for the auth request. The reference server does not currently support POST-based auth, but you can check that the request is correct in the browser.

FI-1567: Support POST auth

---

lib/smart_app_launch/ehr_launch_group_stu2.rb
lib/smart_app_launch/standalone_launch_group_stu2.rb

Use SMARTv2 style scopes by default in the STU2 tests.
Try to running the standalone launch and ehr launch tests. Both should use the SMARTv2 style scopes (e.g. `patient.r`)
Test with Docker using:
```shell
./setup.sh
./run.sh
```
Or directly with a native ruby installation:
```shell
bundle exec inferno migrate
ASYNC_JOBS=false INFERNO_HOST=http://localhost:4567 bundle exec puma
```
The token payload validation methods are based on the requested and received scopes and shouldn't need any changes.
https://github.com/inferno-framework/smart-app-launch-test-kit/blob/170d9fae0961c3c19ec0e7693900e25578db53eb/lib/smart_app_launch/token_payload_validation.rb#L31-L35
We might want to add a ticket to the backlog to make this token refresh subset validation method a little smarter for both STU1 and …

FI-1566: use SMARTv2 scopes

---

README.md
lib/smart_app_launch/token_response_body_test.rb

Addresses [this issue](https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/155) by using config to skip the `check_for_missing_scopes` warning in the Limited Access App group. 
~~Less than ideal solution because it addresses a G10-specific issue within the SMART repo. But, short of replicating this test in G10 within the Limited Access group (which I guess is an option?), this is the best I could come up with and it's a minor change.~~
I tested this change on G10. Here's **2.1.06** passing without warnings:
And here's the warning still showing in **1.2.06** when all the requested scopes are not given:

FI-1650: Remove Warning Message from Limited App Launch

---

lib/smart_app_launch/discovery_stu1_group.rb
spec/smart_app_launch/discovery_group_spec.rb

This branch fixes a nil-safety issue which caused a purple error when `CapabilityStatement.rest.security` was nil (see https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/233).
If you check out the first commit in this branch, the unit tests will fail due to a purple error, which is resolved in the subsequent commit.

FI-1694: Fix discovery group crash

---

lib/smart_app_launch/smart_stu2_suite.rb

If SMART App Launch STU2 is stable, we should remove the 'Work in progress', as it is not a great look when running the g10 test kit locally:
This should just update the title to not include 'Work in Progress'.

Remove (Work in Progress) from title.

---

lib/smart_app_launch/discovery_stu1_group.rb
lib/smart_app_launch/url_helpers.rb
lib/smart_app_launch/well_known_endpoint_test.rb
spec/smart_app_launch/discovery_group_spec.rb
spec/smart_app_launch/url_helpers_spec.rb
spec/smart_app_launch/well_known_endpoint_test_spec.rb

Allows relative SMART URLs in CapabilityStatement and `.well-known/smart-configuration` by turning them into an absolute URL. This PR uses `URI.join` to perform the relative -> absolute expansion. It follows the rules laid out by RFC1808 and RFC 3986.
This means that relative URLs that start with `/` are not considered relative.
e.g.
With a Base URL `http://example.com/fhir`
The relative URL `authorize` becomes  `http://example.com/fhir/authorize`
The relative URL `introspect` becomes  `http://example.com/introspect`
Run the unit tests
`bundle exec rake`
Run the test suite against a configuration endpoint that has relative URLs. A small HTTP server is included below to aid in testing, but feel free to use other means. (Also, if anyone knows a better way I'm all ears!)
- Download …

FI-1717: Handle Relative SMART Links

---

lib/smart_app_launch/token_refresh_test.rb
spec/smart_app_launch/token_refresh_test_spec.rb

Include the original refresh token in the smart credentials output when no new refresh token is received (see https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/377).

FI-1851: Handle refresh without new token

---

lib/smart_app_launch/launch_received_test.rb

The launch received test had the same description as the code received test, which does not make sense.

Update launch test description

---

README.md
lib/smart_app_launch/smart_stu1_suite.rb
lib/smart_app_launch/smart_stu2_suite.rb

Mention FHIR explicitly in suite descriptions and at the top of the readme so that we can put trademark symbols on.
Launch the Test Kit and check that the description was updated in both STU1 and STU2 suites

FI-1954: mention FHIR(r) in descriptions

---

.env
.env.development
Gemfile
Gemfile.lock
config/keycloak/realm-export.json
docker-compose.background.yml
docker-compose.yml
keycloak/realm-export.json
lib/smart_app_launch/smart_stu2_suite.rb
lib/smart_app_launch/token_introspection.rb

This PR presents an opportunity for feedback on a first pass at implementing token introspection tests per JIRA ticket [FI-2080](https://oncprojectracking.healthit.gov/support/browse/FI-2080), based on the [SMART App Launch Token Introspection IG](https://hl7.org/fhir/smart-app-launch/token-introspection.html).  
Currently, these tests are not yet ready for release.  I outline the issues below as well as a recommendation on how to resolve them.  Most of these issues results from having an imperfect reference against which to develop and validate the tests.  Specifically, the existing [Inferno Reference Server](https://github.com/inferno-framework/inferno-reference-server/tree/main) can act as a FHIR server but does not have a real authorization server with token introspection …

FI-2080 Initial token introspection tests

---

.env
.env.development
Gemfile.lock
lib/smart_app_launch/app_redirect_test_stu2.rb
lib/smart_app_launch/smart_stu2_suite.rb
lib/smart_app_launch/token_exchange_test.rb
lib/smart_app_launch/token_introspection.rb
lib/smart_app_launch/token_introspection_access_token_group.rb
lib/smart_app_launch/token_introspection_request_group.rb
lib/smart_app_launch/token_introspection_response_group.rb

[Ticket FI-2251](https://oncprojectracking.healthit.gov/support/browse/FI-2251).  Re-organized test approach and organization based on feedback and discussions with ONC.  Includes an outline for tests, all inputs and outputs, and instructions/descriptions - does not include test bodies or assertions. The goal for this PR is to validate the structure of the tests prior to implementing them.  
This test structure supports 4 different workflows:
1. **Fully automated** - introspects the latest access token (obtained via refresh token) received in standalone launch tests.  This is the easiest and (hopefully) the most common use case.  Executes both Token Introspection Request and Token Introspection Response groups with little to no manual input required from tester.
2. **Automated access …

Fi 2251 input output reorg

---

lib/smart_app_launch/smart_stu2_suite.rb
lib/smart_app_launch/token_exchange_stu2_test.rb
lib/smart_app_launch/token_introspection_request_group.rb
lib/smart_app_launch/token_introspection_response_group.rb

Link to [Jira ticket](https://oncprojectracking.healthit.gov/support/browse/FI-2303)
Completed implementation of token introspection tests and thoroughly tested with a variety of inputs.  Includes all user-facing instructions and documentation.    
- Adding SMART on FHIR discovery tests to group 3.1 adds a constraint that could break 3.2 and 3.3 tests, so I did not add this change as we had discussed
- When SMART on FHIR discovery tests were added to group 3.1, the input field for token introspection endpoint disappeared  from the 3 - Token Introspection Run Tests menu.  The introspection endpoint is needed for group 3.2 (issue introspection request) and the group 3 input menu assumes this will be an automated output from group 3.1 (request new access token).  However, none of the IGs …

FI-2303 token introspection

---

README.md

Updated README to include sections for both Backend Services and Token Introspection, which were missing.  Used the same format as existing groups.
Tests are not impacted.  Can verify markdown format by viewing rendered README for the branch.

FI-2469 README Updates

---

lib/smart_app_launch/discovery_stu1_group.rb

Before running each test, inferno_core now will check each input and will skip the test if an input is required and not populated. This PR fixes some issues that occur in the smart_app_launch test kit as a result, by making some test inputs optional that should not be causing the test to skip when they are not populated.

FI-2470: Make Necessary Inputs Optional for New inferno_core Changes

---

smart_app_launch_test_kit.gemspec

Fixing typo in RubyGems homepage and source_code links for SMART App Launch Test Kit
`gem build smart_app_launch_test_kit.gemspec`
Someone needs to push the gem to the gemserver for fixes to take effect.

Fix RubyGems URLs for homepage and source_code

---

config/nginx.background.conf
config/nginx.conf
docker-compose.background.yml
docker-compose.yml

We're migrating to the HL7 validator wrapper, but the SMART tests don't do any resource validation at all, so instead of adding an unnecessary service this PR just disables the Inferno validator wrapper. Commented out instead of removed entirely in case somebody for some reason wants to enable the validator UI.
All tests should pass using the Reference Server preset.

FI-2429: Disable inferno validator

---

lib/smart_app_launch/smart_stu2_suite.rb
lib/smart_app_launch/token_refresh_stu2_group.rb
lib/smart_app_launch/token_refresh_stu2_test.rb
lib/smart_app_launch/token_refresh_test.rb
spec/smart_app_launch/token_refresh_stu2_spec.rb

This branch updates the token refresh test when using STU2 to support asymmetric client auth.
Use the reference server preset, select asymmetric auth, and set the client id to `SAMPLE_ASYMMETRIC_CLIENT_ID`. The refresh tests should pass, and you can inspect the refresh token requests and see that they are using asymmetric credentials.

FI-2479: Asymmetric token refresh

---

lib/smart_app_launch/well_known_endpoint_test.rb

In the (g)(10) token introspection test, Inferno unexpectedly required and always used the introspection endpoint from the .well-known configuration, even though the introspection endpoint is only recommended to be included in .well-known. The Token Introspection Endpoint input was always ignored, which was problematic because if an introspection endpoint is not returned in .well-known, there is no way to pass the test.
This PR updates the SMART App Launch test kit's well-known test so that it only outputs the introspection endpoint if it is provided in .well-known. This will allow the Token Introspection Endpoint input to be used in (g)(10) if .well-known does not contain an introspection endpoint.
I updated my local Inferno Reference server to not include an introspection endpoint in …

FI-3053: Introspection URL Fix

---

lib/smart_app_launch/token_introspection_group.rb
lib/smart_app_launch/token_introspection_request_group.rb

Updated the custom_authorization_header input to parse out more than one line of input. Changed input to `custom_token introspection_request_header` instead of `custom_authorization_header` and updated the description of the input to be generic instead of specific to the authorization header.
Run the test kit locally and ensure including headers as input in this format:
```
<Header 1 Name>: <Value 1>
<Header 2 Name>: <Value 2>
```
Works as expected.

FI-3018: Allow multi-line custom headers in token introspection request

---

lib/smart_app_launch/app_launch_test.rb
lib/smart_app_launch/app_redirect_test.rb
lib/smart_app_launch/app_redirect_test_stu2.rb
lib/smart_app_launch/token_exchange_test.rb
spec/smart_app_launch/token_exchange_test_spec.rb

Currently, any test kit importing the SMART App Launch tests must configure the url for POST authorization. This branch provides a default for the POST authorization url, as well as the redirect and launch urls so that they will work even when not configured.
Run the US Core tests with SMART App Launch 2/2.2, select POST authorization, and you will receive a purple error. If you point US Core at this branch for the SMART App Launch Test Kit, you should no longer receive a purple error when using POST authorization.

FI-3788: Add default redirect/launch/post auth uris

---

lib/smart_app_launch/backend_services_authorization_group.rb
lib/smart_app_launch/backend_services_authorization_request_success_test.rb
lib/smart_app_launch/backend_services_authorization_response_body_test.rb
lib/smart_app_launch/smart_stu2_2_suite.rb
lib/smart_app_launch/smart_stu2_suite.rb

Updated the Backend Services tests so that they can be used with the token introspection tests. Required adding a few additional outputs to the Backend Services tests and updating smart auth info with some additional fields from the returned Backend Services authentication response.
I tested out running this in the (j)(7) test suite from the j criteria test kit and the Backend Services tests can now be used to run the token introspection test. Note that the token introspection test fails right now because the token introspection response returned when passing in the token received from Backend Services is missing the required `client_id` and `exp` fields.
j criteria MR that uses this change: https://gitlab.mitre.org/inferno/onc-certification-j-criteria-test-kit/-/merge_requests/12

FI-3905: Backend Services Token Introspection Support

---

lib/smart_app_launch/backend_services_invalid_client_assertion_test.rb
lib/smart_app_launch/backend_services_invalid_jwt_test.rb
spec/smart_app_launch/backend_services_invalid_client_assertion_test_spec.rb
spec/smart_app_launch/backend_services_invalid_jwt_test_spec.rb

According to [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2):
>          invalid_client
>               Client authentication failed (e.g., unknown client, no
>               client authentication included, or unsupported
>               authentication method).  The authorization server MAY
>               return an HTTP 401 (Unauthorized) status code to indicate
>               which HTTP authentication schemes are supported.  If the
>               client attempted to authenticate via the "Authorization"
>               request header field, the authorization server MUST
>               respond with an HTTP 401 (Unauthorized) status code and
>               include the "WWW-Authenticate" response header field
>               matching the authentication scheme used …

FI-4013: Allow 401 in invalid client responses in backend services

---

config/presets/SMART_RunClientAgainstServer.json.erb
lib/smart_app_launch/endpoints/mock_smart_server.rb

Fix two typos that resulted in bad error messages in the UI and FHIR responses and update the client preset to use relative hosts.
1. UI typo: run a client tests session selecting the backend services option. Run the Registration test group putting a url that doesn't resolve to a jwks in the "SMART Confidential Asymmetric JSON Web Key Set (JWKS)" input. Verify that the bad url shows up in the error messages.
2. expired token response typo: Run the Client suite selecting the backend services option on localhost:4567 against the server suite as described in the client suite description, but instead of using the access token obtained by the server suite use the following expired access token on the postman read request: eyJjbGllbnRfaWQiOiJzbWFydF9jbGllbnRfdGVzdF9kZW1vIiwiZXhwaXJhdGlvbiI6MTc0N …

Fix typos and presets

---

lib/smart_app_launch/docs/smart_stu2_2_client_suite_description.md
lib/smart_app_launch/endpoints/mock_smart_server.rb
lib/smart_app_launch/endpoints/mock_smart_server/token_endpoint.rb

Currently, token responses require suite options to be setup. Now, if a suite only offers backend services, like the bulk test kit, then no suite options need to be defined.
- run rspec
- test as a part of the [bulk data client auth PR](https://github.com/inferno-framework/bulk-data-test-kit/pull/48)

FI-3973: decouple client credentials tokens from suite options

---

Gemfile.lock
lib/smart_app_launch/ehr_launch_group.rb
lib/smart_app_launch/standalone_launch_group.rb

This PR fixes FI-4079 SMART v1 test configuration shall default to pkce be disabled
Add configuration to set PKCE as disabled for SMART v1 EHR launch test and Standalone launch test
Run "SMART App Launch STU1" Test Suite
Do NOT select preset
Verify that PKCE Disabled is selected for "SMART App Launch STU1", "Standalone Launch", and "EHR Launch"

FI-4079 Disable PKCE for SMART v1 test by default
